---

- name: Install Atom IDE packages
  command: "{{ item }}"
  with_items:
    - "apm install atom-beautify"
    - "apm install autocomplete-python"
    - "apm install highlight-selected"
    - "apm install language-powershell"
    - "apm install language-terraform"
    - "apm install linter"
    - "apm install linter-flake8"
    - "sudo npm install -g node-gyp"
    - "apm install platformio-ide-terminal"
    - "apm install python-debugger"
    - "apm install script"
  ignore_errors: yes
  tags:
    - apm
