---

- name: Add notepadqq rep
  apt_repository:
    repo: 'ppa:notepadqq-team/notepadqq'

- name: Update cache if greater than 3600 seconds (1 hour)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages on Debian based
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - baobab
    - dkms
    - network-manager-openconnect
    - network-manager-openconnect-gnome
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-vpnc
    - network-manager-vpnc-gnome
    - notepadqq
    - remmina
    - samba
    - tmux
    - usb-creator-gtk
    - virt-manager
    - virtualbox
    - virtualbox-dkms
    - vlc
    - wireshark
    - xubuntu-desktop
    - zenmap

- name: Download atom
  get_url:
    url: "{{ atom_source_location }}"
    dest: "{{ atom_download_destination }}"
    mode: "0774"
  register: atom_downloaded
  tags:
    - deb
    - atom

- name: Install atom package
  apt:
    deb: "{{ atom_download_destination }}"
  when: atom_downloaded.changed
  tags:
    - deb
    - atom

- name: Download vagrant
  get_url:
    url: "{{ vagrant_source_location }}"
    dest: "{{ vagrant_download_destination }}"
    checksum: "sha256:{{ vagrant_checksum }}"
    mode: "0774"
  register: vagrant_downloaded
  tags:
    - deb
    - vagrant

- name: Install vagrant package
  apt:
    deb: "{{ vagrant_download_destination }}"
  when: vagrant_downloaded.changed
  tags:
    - deb
    - vagrant
