---

- name: Ensure github.com is a known host
  lineinfile:
    dest: "{{ known_hosts_file }}"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Change owner of known_hosts
  file:
    path: "{{ known_hosts_file }}"
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: 0644

- name: Create git repo directory
  file:
    path: "{{ git_repo_folder }}"
    state: directory
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: 0755

- name: Download git repos
  git:
    repo: "{{ item.repo}}"
    dest: "{{ item.folder }}"
    update: no
  with_items:
    - { repo: 'https://github.com/andrew-j-price/ansible-freetds.git', folder: '{{ git_repo_folder }}/ansible-freetds' }
    - { repo: 'https://github.com/andrew-j-price/ansible-mysql-deploy-secure.git', folder: '{{ git_repo_folder }}/ansible-mysql-deploy-secure' }
    - { repo: 'https://github.com/andrew-j-price/ansible-windows-nsclient.git', folder: '{{ git_repo_folder }}/ansible-windows-nsclient' }
    - { repo: 'https://github.com/andrew-j-price/atomic-fun.git', folder: '{{ git_repo_folder }}/atomic-fun' }
    - { repo: 'https://github.com/andrew-j-price/dabbling.git', folder: '{{ git_repo_folder }}/dabbling' }
    - { repo: 'https://github.com/andrew-j-price/DAM-docker-is-fun.git', folder: '{{ git_repo_folder }}/dam-docker-is-fun' }
    - { repo: 'https://github.com/andrew-j-price/duplo-building-blocks.git', folder: '{{ git_repo_folder }}/duplo-building-blocks' }
    - { repo: 'https://github.com/andrew-j-price/mssql-essentials.git', folder: '{{ git_repo_folder }}/mssql-essentials' }
    - { repo: 'https://github.com/andrew-j-price/node-redis-mongo.git', folder: '{{ git_repo_folder }}/node-redis-mongo' }
    - { repo: 'https://github.com/andrew-j-price/python-flask.git', folder: '{{ git_repo_folder }}/python-flask' }
    - { repo: 'https://github.com/andrew-j-price/toolchain.git', folder: '{{ git_repo_folder }}/toolchain' }

- name: Ensure correct owner on git folder
  file:
    path: "{{ git_repo_folder }}"
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    state: directory
    recurse: yes
