---

- name: Update cache if greater than 3600 seconds (1 hour)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Enable Ansible ppa repo
  apt_repository:
    repo: 'ppa:ansible/ansible'

- name: Add Docker apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: add Docker Debian based repo
  apt_repository:
    repo: 'deb https://get.docker.com/ubuntu docker main'
    state: present

- name: Install packages on Debian based
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - curl
    - dpkg
    - expect
    - freetds-bin
    - freetds-dev
    - gcc
    - git
    - git-review
    - lxc-docker
    - ldap-utils
    - make
    - monit
    - mysql-client
    - netcat-openbsd
    - nmap
    - openssh-server
    - pcregrep
    - python-ceilometerclient
    - python-cinderclient
    - python-dev
    - python-glanceclient
    - python-heatclient
    - python-keystoneclient
    - python-neutronclient
    - python-novaclient
    - python-openstackclient
    - python-pip
    - python-swiftclient
    - python-troveclient
    - software-properties-common
    - sslscan
    - tcpdump
    - vim
    - virtualbox
    - wget

- name: Install packages via pip on Ubuntu based
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - PyYAML
    - setuptools
    - shade
    - six

- name: Download vagrant for Debian
  get_url:
    url: "{{ vagrant_package_debian_source }}"
    dest: "{{ vagrant_package_debian_install }}"
    mode: 0744

- name: Install deb packages
  apt:
    deb: "{{ item }}"
  with_items:
    - "{{ vagrant_package_debian_install }}"

- name: Start the service and enable on startup on Debian based systems
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker
