---

- name: Install python and dependencies for Ansible modules on Fedora
  raw: dnf install -y python2 python2-dnf libselinux-python

- name: Get Virtualbox yum repo for Fedora
  get_url:
    url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo
    mode: 0644

- name: Install packages on Fedora based
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - docker
    - firefox
    - freetds
    - freetds-devel
    - gcc
    - git
    - git-review
    - make
    - mariadb
    - monit
    - nc
    - nmap
    - openldap-clients
    - openssh-server
    - python-devel
    - python-httplib2
    - python-jinja2
    - python-keyczar
    - python-paramiko
    - python-pip
    - python-setuptools
    - python-ceilometerclient
    - python-cinderclient
    - python-glanceclient
    - python-heatclient
    - python-keystoneclient
    - python-neutronclient
    - python-novaclient
    - python-openstackclient
    - python-pip
    - python-swiftclient
    - python-troveclient
    - PyYAML
    - tcpdump
    - vim
    - VirtualBox-5.0
    - wget
    - wireshark-gnome

- name: Install packages via pip on Fedora based
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - shade

- name: Download vagrant for Fedora
  get_url:
    url: "{{ vagrant_package_rhel_source }}"
    dest: "{{ vagrant_package_rhel_install }}"
    mode: 0744

- name: Install rpm packages via dnf on Fedora
  dnf:
    name: "{{ item }}"
  with_items:
    - "{{ vagrant_package_rhel_install }}"

- name: Start the service and enable on startup on Fedora based systems
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker
