---

- name: ensure github.com is a known host
  lineinfile:
    dest: "{{ known_hosts_file }}"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: change owner of known_hosts
  file: 
    path: "{{ known_hosts_file }}"
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: 0644

- name: Create git repo directory
  file: 
    path: "{{ git_repo_folder }}"
    state: directory 
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: 0755

- name: download git repo
  git: 
    repo: "https://github.com/andrew-j-price/ansible-freetds.git"
    dest: "{{ git_repo_folder }}/ansible-freetds"
    update: no

- name: download git repo
  git: 
    repo: "https://github.com/andrew-j-price/ansible-haproxy.git"
    dest: "{{ git_repo_folder }}/ansible-haproxy"
    update: no

- name: download git repo
  git: 
    repo: "https://github.com/andrew-j-price/ansible-mysql-deploy-secure.git"
    dest: "{{ git_repo_folder }}/ansible-mysql-deploy-secure"
    update: no

- name: download git repo
  git: 
    repo: "https://github.com/andrew-j-price/ansible-windows-nsclient.git"
    dest: "{{ git_repo_folder }}/ansible-windows-nsclient"
    update: no

- name: download git repo
  git: 
    repo: "https://github.com/andrew-j-price/docker-monit-ansible.git"
    dest: "{{ git_repo_folder }}/docker-monit-ansible"
    update: no

- name: download git repo
  git: 
    repo: "https://github.com/andrew-j-price/toolchain.git"
    dest: "{{ git_repo_folder }}/toolchain"
    update: no

- name: download git repo
  git: 
    repo: "https://github.com/andrew-j-price/vagrant-ansible-building-blocks.git"
    dest: "{{ git_repo_folder }}/vagrant-ansible-building-blocks"
    update: no

#- name: Ensure owner is set correctly # needed for Vagrant provisioning
#  shell: chown -R {{ my_user }}:{{ my_group }} {{ git_repo_folder }}
